{% set name = "persistent" %}
{% set version = "4.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/persistent-{{ version }}.tar.gz
  sha256: a6215221feb3955d485fa90c7bcec4fb29650ce39ca3d0c1126710392e0dc2dc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi
    - pip
    - python
  run:
    - cffi
    - python
    - zope.interface

test:
  imports:
    - persistent
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/persistent/
  summary: Translucent persistent objects
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
