{% set name = "persistent" %}
{% set version = "6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/persistent-{{ version }}.tar.gz
  sha256: 083650c0ffedcb880328963c294b9511a02b6b05e421e737a7d55f9eed88fb5f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cffi
    - pip
    - python
  run:
    - cffi
    - python
    - zope.interface

test:
  imports:
    - persistent
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/persistent/
  summary: Translucent persistent objects
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
