{% set name = "persistent" %}
{% set version = "4.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/persistent-{{ version }}.tar.gz
  sha256: f23eb25ea45bbca6bf6204b028a0a7eaa173d2781d68ff57cd5861cc1a0d0ed0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi
    - pip
    - python
  run:
    - cffi
    - python
    - zope.interface

test:
  imports:
    - persistent
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/persistent/
  summary: Translucent persistent objects
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
