schema_version: 1

context:
  version: "6.8"

package:
  name: persistent
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/persistent/persistent-${{ version }}.tar.gz
  sha256: 2e7ccaa1b1ab5346be903980bf74ac301e5a7be4e6949c93cf9f2a716add8b18

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools
    - cffi
    - pip
  run:
    - python
    - zope.deferredimport
    - zope.interface
    - cffi

tests:
  - python:
      imports:
        - persistent
      pip_check: true
  - requirements:
      run:
        - python
        - manuel
    script:
      - python -m unittest discover -b -v persistent

about:
  summary: Translucent persistent objects
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  homepage: https://github.com/zopefoundation/persistent/
  documentation: https://persistent.readthedocs.io

extra:
  recipe-maintainers:
    - osamples
    - izahn
    - mgorny
